//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search
    {
        public int search_id { get; set; }
        public string search_key { get; set; }
        public Nullable<int> search_count { get; set; }
        public Nullable<System.DateTime> search_date { get; set; }
    }
}
