//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicePack()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int servicepack_id { get; set; }
        public string servicepack_title { get; set; }
        public string servicepack_description { get; set; }
        public Nullable<decimal> servicepack_listedprice { get; set; }
        public Nullable<decimal> servicepack_actualprice { get; set; }
        public string servicepack_unit { get; set; }
        public Nullable<bool> servicepack_users { get; set; }
        public Nullable<bool> servicepack_emloyers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
