//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmitCV
    {
        public int submitcv_id { get; set; }
        public Nullable<int> work_id { get; set; }
        public Nullable<System.DateTime> submitcv_datesubmit { get; set; }
        public Nullable<int> cv_id { get; set; }
    
        public virtual Work Work { get; set; }
        public virtual Cv Cv { get; set; }
    }
}
