//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public string user_email { get; set; }
        public string user_pass { get; set; }
        public string user_name { get; set; }
        public Nullable<bool> user_active { get; set; }
        public Nullable<bool> user_del { get; set; }
        public Nullable<System.DateTime> user_datecreate { get; set; }
        public Nullable<System.DateTime> user_datelogin { get; set; }
        public string user_img { get; set; }
        public Nullable<bool> user_sex { get; set; }
        public string user_interests { get; set; }
    }
}
