//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWork.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Layout
    {
        public int layout_id { get; set; }
        public string ct_1 { get; set; }
        public string ct_2 { get; set; }
        public string ct_3 { get; set; }
        public string ct_4 { get; set; }
        public string ct_5 { get; set; }
        public string ct_6 { get; set; }
        public string ct_7 { get; set; }
        public string ct_8 { get; set; }
        public string ct_9 { get; set; }
        public string ct_10 { get; set; }
        public string ct_11 { get; set; }
        public string ct_12 { get; set; }
        public string ct_13 { get; set; }
        public string ct_14 { get; set; }
        public string ct_15 { get; set; }
        public string ct_16 { get; set; }
        public string ct_17 { get; set; }
        public string ct_18 { get; set; }
        public string ct_19 { get; set; }
        public string ct_20 { get; set; }
        public string ct_21 { get; set; }
        public string ct_22 { get; set; }
        public string ct_23 { get; set; }
        public string ct_24 { get; set; }
        public string ct_25 { get; set; }
    }
}
