//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWork.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int news_id { get; set; }
        public string news_title { get; set; }
        public string news_image { get; set; }
        public string news_contents { get; set; }
        public string news_tags { get; set; }
        public Nullable<System.DateTime> news_datepost { get; set; }
        public Nullable<int> news_views { get; set; }
    }
}
